# Assignment Sesi 10
Nama: Faraday Barr Fatahillah

Instruksi

Anda baru bergabung sebagai data analyst di divisi Business Intelligence sebuah perusahaan telekomunikasi. Tim meminta Anda membersihkan dataset pelanggan sebelum dataset tersebut dipakai untuk model prediksi churn.

Dataset: https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv

**Task 1 — Audit kualitas data awal**

1. Load dataset ke variabel df. Cetak shape, tipe data setiap kolom, dan 5 baris pertama.
2. Hitung jumlah missing values standar (NaN) per kolom. Tampilkan hanya kolom yang punya missing value, diurutkan dari terbanyak.
3. Cek kolom TotalCharges: kolom ini seharusnya bertipe numerik. Temukan kenapa ada baris yang tidak bisa dikonversi ke float. Cetak baris-baris bermasalah tersebut.
4. Cek kolom SeniorCitizen: nilai yang ada hanya 0 dan 1, tapi ini kolom numerik. Apakah ada nilai di luar 0 dan 1? Cetak hasilnya.
5. Buat ringkasan audit dalam cell markdown: kolom mana yang punya masalah kualitas data, apa jenis masalahnya, dan berapa jumlah baris yang terdampak.

In [184]:
import pandas as pd
import numpy as np

#Task 1.1
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url, na_values=["NA", "N/A", "null", "?", "-", " "])

print(f'Shape: {df.shape}')

df.head(5)

Shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [185]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.1 MB

In [186]:
#Task 1.2
df.isna().sum().sort_values(ascending=False)

TotalCharges        11
gender               0
SeniorCitizen        0
Partner              0
customerID           0
Dependents           0
tenure               0
MultipleLines        0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
InternetService      0
TechSupport          0
StreamingTV          0
Contract             0
StreamingMovies      0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
Churn                0
dtype: int64

In [187]:
#Task 1.3
"""
Seharusnya tidak ada data yang tidak bisa dikonversi ke float karena sudah float semua sesuai dengan df.info() di atas
""" 

df['TotalCharges_numeric'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.query('TotalCharges_numeric.isna()')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No,NaN
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No,NaN
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No,NaN
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No,NaN
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No,NaN
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No,NaN
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No,NaN
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No,NaN
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No,NaN
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No,NaN
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No,NaN

In [188]:
#Task 1.4
df['SeniorCitizen'].unique()

array([0, 1])

#Task 1.5\
Answer:\
Masalah yang ada pada data ini adalah adanya missing values di kolom 'TotalCharges' dan terdapat 11 baris yang terdampak

**Task 2 — Deteksi non-standard dan unexpected missing values**
1. Cek seluruh kolom bertipe object. Untuk setiap kolom tersebut, tampilkan unique values-nya. Identifikasi nilai-nilai yang berfungsi sebagai placeholder kosong (contoh: string spasi, 'No internet service', 'No phone service').
2. Tentukan: apakah nilai 'No internet service' dan 'No phone service' harus diperlakukan sebagai missing value atau sebagai kategori valid? Tulis alasan Anda di cell markdown (1-2 kalimat).
3. Cek kolom tenure: apakah ada nilai 0 yang tidak masuk akal dalam konteks bisnis (pelanggan dengan tenure 0 bulan)? Berapa jumlah barisnya?

In [189]:
#Task 2.1
obj_col = df.select_dtypes(include='object').columns

for col in obj_col:
    print(f"\nKolom: {col}")
    print(df[col].unique())

Kolom: customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str

Kolom: gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

Kolom: Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Kolom: Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Kolom: PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Kolom: MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

Kolom: InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

Kolom: OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Kolom: OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

Kolom: DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Kolom: TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Kolom: StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Kolom: StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Kolom: Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

Kolom: PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Kolom: PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

Kolom: Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

C:\Users\bobe\AppData\Local\Temp\ipykernel_24420\475986239.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_col = df.select_dtypes(include='object').columns

#Task 2.2\
Bisa digunakan sebagai valid values karena bisa menjadi informasi tambahan mengenai kondisi pelanggan yang tidak menggunakan layanan tersebut.

In [190]:
#Task 2.3
tenure_zero = df[df['tenure'] == 0]

tenure_zero

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No,NaN
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No,NaN
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No,NaN
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No,NaN
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No,NaN
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No,NaN
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No,NaN
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No,NaN
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No,NaN
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No,NaN
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No,NaN

Answer:\
Pelanggan yang memiliki nilai tenure sama dengan 0 memiliki nilai TotalCharges sama dengan null. Artinya mereka belum melakukan transaksi terhadap layanan sama sekali.

**Task 3 — Penanganan missing values**
1. Konversi kolom TotalCharges ke float. Baris yang tidak bisa dikonversi otomatis menjadi NaN. Simpan hasilnya ke kolom yang sama.
2. Isi missing values pada kolom TotalCharges menggunakan median. Jelaskan di markdown kenapa median lebih tepat dari mean untuk kolom ini.
3. Untuk kolom tenure dengan nilai 0: ganti dengan NaN, lalu isi menggunakan nilai median tenure pelanggan yang memiliki produk dan layanan yang sama (gunakan groupby berdasarkan InternetService dan PhoneService sebagai proxy).
4. Verifikasi: setelah cleaning, tidak ada lagi missing values di kolom TotalCharges dan tenure. Cetak konfirmasi dengan isnull().sum() untuk kedua kolom tersebut.

In [191]:
#Task 3.1 
df['TotalCharges'] = df['TotalCharges'].astype('float')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customerID            7043 non-null   str
 1   gender                7043 non-null   str
 2   SeniorCitizen         7043 non-null   int64
 3   Partner               7043 non-null   str
 4   Dependents            7043 non-null   str
 5   tenure                7043 non-null   int64
 6   PhoneService          7043 non-null   str
 7   MultipleLines         7043 non-null   str
 8   InternetService       7043 non-null   str
 9   OnlineSecurity        7043 non-null   str
 10  OnlineBackup          7043 non-null   str
 11  DeviceProtection      7043 non-null   str
 12  TechSupport           7043 non-null   str
 13  StreamingTV           7043 non-null   str
 14  StreamingMovies       7043 non-null   str
 15  Contract              7043 non-null   str
 16  PaperlessBilling      7043 non-null   str
 17  PaymentMethod         7043 non-null   str
 18  MonthlyCharges        7043 non-null   float64
 19  TotalCharges          7032 non-null   float64
 20  Churn                 7043 non-null   str
 21  TotalCharges_numeric  7032 non-null   float64
dtypes: float64(3), int64(2), str(17)
memory usage: 1.2 MB

In [192]:
df['TotalCharges'].value_counts(ascending=True)

TotalCharges
29.85       1
1889.50     1
108.15      1
1840.75     1
151.65      1
           ..
19.90       8
20.05       8
19.65       8
19.75       9
20.20      11
Name: count, Length: 6530, dtype: int64

In [193]:
#Mean sebelum null value berubah menjadi median/mean
df['TotalCharges'].mean()

np.float64(2283.3004408418656)

In [194]:
#Task 3.2
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

# Uncomment line di bawah dan comment line di atas kemudian run all untuk cek perubahan
# df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())

df.query('TotalCharges_numeric.isna()')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,1397.475,No,NaN
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,1397.475,No,NaN
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,1397.475,No,NaN
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,1397.475,No,NaN
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,1397.475,No,NaN
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,1397.475,No,NaN
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,1397.475,No,NaN
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,1397.475,No,NaN
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,1397.475,No,NaN
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,No,Two year,No,Mailed check,73.35,1397.475,No,NaN
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,1397.475,No,NaN

Median lebih baik untuk data yang kurang simetris sehingga tidak bias ke rata-rata atau data dengan value yang tinggi

In [195]:
#Mean setelah null value berubah menjadi median/mean
df['TotalCharges'].mean()

np.float64(2281.9169281556156)

In [196]:
df.query('tenure == 0.0')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,1397.475,No,NaN
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,1397.475,No,NaN
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,1397.475,No,NaN
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,1397.475,No,NaN
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,1397.475,No,NaN
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,1397.475,No,NaN
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,1397.475,No,NaN
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,1397.475,No,NaN
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,1397.475,No,NaN
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,No,Two year,No,Mailed check,73.35,1397.475,No,NaN
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,1397.475,No,NaN

In [197]:
#Task 3.3
df.loc[df['tenure'] == 0, 'tenure'] = pd.NA

df['tenure'] = df.groupby(
    ['InternetService', 'PhoneService']
)['tenure'].transform(lambda x: x.fillna(x.median()))

df.query('TotalCharges_numeric.isna()')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalCharges_numeric
488,4472-LVYGI,Female,0,Yes,Yes,29.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,1397.475,No,NaN
753,3115-CZMZD,Male,0,No,Yes,25.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,1397.475,No,NaN
936,5709-LVOEQ,Female,0,Yes,Yes,30.0,Yes,No,DSL,Yes,...,No,Yes,Yes,Two year,No,Mailed check,80.85,1397.475,No,NaN
1082,4367-NUYAO,Male,0,Yes,Yes,25.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,1397.475,No,NaN
1340,1371-DWPAZ,Female,0,Yes,Yes,29.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,1397.475,No,NaN
3331,7644-OMVMY,Male,0,Yes,Yes,25.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,1397.475,No,NaN
3826,3213-VVOLG,Male,0,Yes,Yes,25.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,1397.475,No,NaN
4380,2520-SGTTA,Female,0,Yes,Yes,25.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,1397.475,No,NaN
5218,2923-ARZLG,Male,0,Yes,Yes,25.0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,1397.475,No,NaN
6670,4075-WKNIU,Female,0,Yes,Yes,30.0,Yes,Yes,DSL,No,...,Yes,Yes,No,Two year,No,Mailed check,73.35,1397.475,No,NaN
6754,2775-SEFEE,Male,0,No,Yes,30.0,Yes,Yes,DSL,Yes,...,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,1397.475,No,NaN

In [198]:
df = df.drop(columns=['TotalCharges_numeric'])
df.isna().sum().sort_values()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

**Task 4 — Laporan cleaning**

Di cell markdown di akhir notebook, buat tabel ringkasan cleaning dengan format berikut (tulis sebagai teks, bukan tabel markdown):

```
Kolom          | Masalah Ditemukan              | Penanganan          | Baris Terdampak

TotalCharges   | String kosong/spasi            | Konversi + isi median | X baris

tenure         | Nilai 0 tidak valid            | Ganti NaN + isi groupby | Y baris
```
 

Isi angka X dan Y dengan jumlah baris yang sebenarnya dari dataset Anda.

Answer:

Masalah yang ditemukan:
1. Total Charges = terdapat missing value
2. Tenure = nilai 0 tidak valid dalam konteks berlangganan

Penanganan:
1. Total Charges = mengisi dengan median
2. Tenure = mengganti 0 dengan median dan group dengan 'InternetService' dan 'PhoneService'

Baris terdampak:
1. Total Charges = 11 baris
2. Tenur = 11 baris